<form name="vehicles_form" method="post" action="<?php echo $_SERVER['REQUEST_URI']; ?>">
	<fieldset>
		<legend>Vehicle Information</legend>
		<ol>
			<li>
				<label for="vehicle_year">Year:</label>
				<input type="text" name="vehicle_year" id="vehicle_year" value="<?php echo $this->info['year_value']; ?>" size="4" required="required">
			</li>
			<li>
				<label for="vehicle_make">Make:</label>
				<input type="text" name="vehicle_make" id="vehicle_make" value="<?php echo $this->info['make_value']; ?>" required="required">
			</li>
			<li>
				<label for="vehicle_model">Model:</label>
				<input type="text" name="vehicle_model" id="vehicle_model" value="<?php echo $this->info['model_value']; ?>" required="required">
			</li>
			<li>
				<label for="vehicle_price">Price:</label>
				<input type="text" name="vehicle_price" id="vehicle_price" value="<?php echo $this->info['vehicle_price']; ?>" required="required">
			</li>
			<li>
				<label for="vehicle_description">Description:</label>
				<textarea name="vehicle_description" id="vehicle_description" rows="6" cols="40" required="required"><?php echo $this->info['vehicle_description']; ?></textarea>
			</li>
		</ol>
	</fieldset>
	<fieldset>
		<legend>Customer Information</legend>
		<ol>
			<li>
				<label for="customer_first_name">First Name:</label>
				<input type="text" name="customer_first_name" id="customer_first_name" value="<?php echo $this->info['customer_first_name']; ?>" size="30" required="required">
			</li>
			<li>
				<label for="customer_last_name">Last Name:</label>
				<input type="text" name="customer_last_name" id="customer_last_name" value="<?php echo $this->info['customer_last_name']; ?>" size="30" required="required">
			</li>
			<li>
				<label for="customer_phone_number">Phone Number:</label>
				<input type="text" name="customer_phone_number" id="customer_phone_number" value="<?php echo $this->info['customer_phone_number']; ?>" required="required">
			</li>
			<li>
				<label for="customer_email_address">E-mail Address:</label>
				<input type="text" name="customer_email_address" id="customer_email_address" value="<?php echo $this->info['customer_email_address']; ?>" size="30" required="required">
			</li>
		</ol>
	</fieldset>
	<fieldset>
		<legend>Advertisement Information</legend>
		<ol>
			<li>
				<label for="ad_cost">Cost:</label>
				<input type="text" name="ad_cost" id="ad_cost" value="<?php echo $this->info['ad_cost']; ?>" required="required">
			</li>
		</ol>
	</fieldset>
	<fieldset>
		<legend>Credit Card Information</legend>
		<ol>
			<li>
				<label for="credit_card_number">Card Number:</label>
				<input type="text" name="credit_card_number" id="credit_card_number" value="<?php echo $this->info['ad_card_number']; ?>" required="required">
			</li>
			<li>
				<label for="credit_card_expiration_date">Expiration Date:</label>
				<input type="text" name="credit_card_expiration_date" id="credit_card_expiration_date" value="<?php echo $this->info['ad_card_expiration_date']; ?>" size="5" required="required">
			</li>
			<li>
				<label for="credit_card_cvv">Card CVV Number:</label>
				<input type="text" name="credit_card_cvv" id="credit_card_cvv" value="<?php echo $this->info['ad_card_cvv']; ?>" size="4" required="required">
			</li>
		</ol>
	</fieldset>
	<p><button type="submit">Save</button></p>
</form>