<!doctype html>
<html>
	<head>
		<title>Dominion Enterprises Test | <?php echo $this->title; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="robots" content="noindex, nofollow">
		<link rel="stylesheet" type="text/css" href="/css/layout.css">
		<!--[if lt IE 9]><script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	</head>
	<body>
		<header><a href="/">Dominion Enterprises Test</a></header>
		<nav>
			<a href="/">Home</a>
			<a href="/vehicles">Vehicles</a>
		</nav>
		<div id="content">
			<?php echo $this->content;?>
		</div>
		<footer>&copy;<?php echo date('Y'); ?> Dominion Enterprises Test.  All rights reserved.</footer>
	</body>
</html>